import localFont from "next/font/local";
import "./globals.css";
import MainHeader from "@/components/MainHeader";

export const metadata = {
  title: "Geeta daily",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-[#FF8000]">
        <MainHeader />
        {children}
      </body>
    </html>
  );
}
